### PR TITLE
Restructured dashboard screen | Allow individual columns to be scrollable

### PR DESCRIPTION
**Pull request by elcruzo**

### CODE REVIEW

**Comment by ahdahl** [comment]
Please add a screenshot or screen recording of the change as a test plan

**Comment by elcruzo** [comment]
<div>
    <a href="https://www.loom.com/share/88bce7945579492d93af81ecd1b681eb">
      <p>Demo Video</p>
    </a>
    <a href="https://www.loom.com/share/88bce7945579492d93af81ecd1b681eb">
      
    </a>
  </div>

**Comment by prati21913** [comment]
Thanks for attaching the video, looks good!

**Comment by prati21913** [comment]
@elcruzo coupe of nit-picky things for future commits: 

1. Restructured dashboard screen is a great title for the PR! In the future, you can also think about adding more technical details (in line comments) like why a particular piece of code was changed or what was the reasoning behind the change(if the change is complex). This will help you in the future in case you want to look back and understand your thought process while building this commit. eg: you make a PR, it gets approved but 2 weeks later, you want to revert to old design. Having those comments might help! 

2. Modular div(s). ListenerDashboard is a loooooong div file haha. in the future, if you get time, it would be nice to clean up and make left col for example into its const/function that you call. This will make your code more readable, modular, and much easier to maintain! I understand we are in the rush to finish the milestones, so no worries for now :) 

Overall, looking very awesome and excited to see where you take this! Great work 🥳

**Comment by elcruzo** [comment]
> @elcruzo coupe of nit-picky things for future commits:
> 
> 1. Restructured dashboard screen is a great title for the PR! In the future, you can also think about adding more technical details (in line comments) like why a particular piece of code was changed or what was the reasoning behind the change(if the change is complex). This will help you in the future in case you want to look back and understand your thought process while building this commit. eg: you make a PR, it gets approved but 2 weeks later, you want to revert to old design. Having those comments might help!
> 2. Modular div(s). ListenerDashboard is a loooooong div file haha. in the future, if you get time, it would be nice to clean up and make left col for example into its const/function that you call. This will make your code more readable, modular, and much easier to maintain! I understand we are in the rush to finish the milestones, so no worries for now :)
> 
> Overall, looking very awesome and excited to see where you take this! Great work 🥳

Got it! I'll make more inline comments going forward. Thanks!

**Pull request merged**
